development:
  adapter: postgresql
  encoding: unicode
  database: twistrecipes_development
  pool: 5
  username: elangobalusamy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: twistrecipes_test
  pool: 5
  username: elangobalusamy
  password:
